/**
 * run command
 * @generated from apis/ai/schema.ts
 */
import { Cloudflare } from '@cloudflare/sdk';
import type { ArgumentsCamelCase, Argv, CommandModule } from 'yargs';
import { getAccountId, getAuthToken } from '../../../lib/auth.js';
import { getDefaultHeaders } from '../../../lib/request-headers.js';
import { handleError } from '../../../lib/errors.js';
import { formatOutput } from '../../../lib/output.js';
import { validateResourceId, validateStringInput } from '../../../lib/input-validation.js';
import { formatDryRun } from '../../../lib/dry-run.js';
import { parseBody, setNestedValue } from '../../../lib/body-parser.js';

interface RunArgs {
  modelName: string;
  text?: string;
  guidance?: number;
  height?: number;
  image?: string;
  'image-b64'?: string;
  mask?: string;
  'negative-prompt'?: string;
  'num-steps'?: number;
  prompt?: string;
  seed?: number;
  strength?: number;
  width?: number;
  lang?: string;
  'source-lang'?: string;
  'target-lang'?: string;
  'input-text'?: string;
  'max-length'?: number;
  fields?: string;
  ndjson?: boolean;
  dryRun?: boolean;
  body?: string;
  accountId?: string;
}

const command: CommandModule<object, RunArgs> = {
  command: 'run <modelName>',
  describe:
    'This endpoint provides users with the capability to run specific AI models on-demand. By submitting the required input data, users can receive real-time predictions or results generated by the chosen AI model. The endpoint supports various AI model types, ensuring flexibility and adaptability for diverse use cases. Model specific inputs available in [Cloudflare Docs](https://developers.cloudflare.com/workers-ai/models/).',

  builder: (yargs: Argv): Argv<RunArgs> => {
    return yargs
      .positional('modelName', {
        type: 'string',
        description: 'Model name',
        demandOption: true,
      })
      .option('text', {
        type: 'string',
        description: 'The text that you want to classify',
        default: undefined,
      })
      .option('guidance', {
        type: 'number',
        description:
          'Controls how closely the generated image should adhere to the prompt; higher values make the image more aligned with the prompt',
        default: undefined,
      })
      .option('height', {
        type: 'number',
        description: 'The height of the generated image in pixels',
        default: undefined,
      })
      .option('image', {
        type: 'string',
        description:
          'For use with img2img tasks. An array of integers that represent the image data constrained to 8-bit unsigned integer values',
        default: undefined,
      })
      .option('image-b64', {
        type: 'string',
        description: 'For use with img2img tasks. A base64-encoded string of the input image',
        default: undefined,
      })
      .option('mask', {
        type: 'string',
        description:
          'An array representing An array of integers that represent mask image data for inpainting constrained to 8-bit unsigned integer values',
        default: undefined,
      })
      .option('negative-prompt', {
        type: 'string',
        description: 'Text describing elements to avoid in the generated image',
        default: undefined,
      })
      .option('num-steps', {
        type: 'number',
        description: 'The number of diffusion steps; higher values can improve quality but take longer',
        default: undefined,
      })
      .option('prompt', {
        type: 'string',
        description: 'A text description of the image you want to generate',
        default: undefined,
      })
      .option('seed', {
        type: 'number',
        description: 'Random seed for reproducibility of the image generation',
        default: undefined,
      })
      .option('strength', {
        type: 'number',
        description:
          'A value between 0 and 1 indicating how strongly to apply the transformation during img2img tasks; lower values make the output closer to the input image',
        default: undefined,
      })
      .option('width', {
        type: 'number',
        description: 'The width of the generated image in pixels',
        default: undefined,
      })
      .option('lang', {
        type: 'string',
        description: "The speech language (e.g., 'en' for English, 'fr' for French). Defaults to 'en' if not specified",
        default: undefined,
      })
      .option('source-lang', {
        type: 'string',
        description: "The language code of the source text (e.g., 'en' for English). Defaults to 'en' if not specified",
        default: undefined,
      })
      .option('target-lang', {
        type: 'string',
        description: "The language code to translate the text into (e.g., 'es' for Spanish)",
        default: undefined,
      })
      .option('input-text', {
        type: 'string',
        description: 'The text that you want the model to summarize',
        default: undefined,
      })
      .option('max-length', {
        type: 'number',
        description: 'The maximum length of the generated summary in tokens',
        default: undefined,
      })
      .option('fields', {
        type: 'string',
        description: 'Comma-separated list of fields to include in output',
      })
      .option('ndjson', {
        type: 'boolean',
        description: 'Output as newline-delimited JSON (one object per line)',
        default: false,
      })
      .option('dry-run', {
        type: 'boolean',
        description: 'Validate and show what would happen without executing',
        default: false,
      })
      .option('body', {
        type: 'string',
        description: 'Raw JSON request body (bypasses individual flags)',
      })
      .conflicts('text', [
        'guidance',
        'height',
        'image',
        'imageB64',
        'mask',
        'negativePrompt',
        'numSteps',
        'prompt',
        'seed',
        'strength',
        'width',
        'lang',
        'inputText',
        'maxLength',
      ])
      .implies('text', ['targetLang'])
      .conflicts('guidance', ['text', 'lang', 'sourceLang', 'targetLang', 'inputText', 'maxLength'])
      .conflicts('height', ['text', 'lang', 'sourceLang', 'targetLang', 'inputText', 'maxLength'])
      .conflicts('image', ['text', 'lang', 'sourceLang', 'targetLang', 'inputText', 'maxLength', 'prompt'])
      .conflicts('image-b64', ['text', 'lang', 'sourceLang', 'targetLang', 'inputText', 'maxLength'])
      .conflicts('mask', ['text', 'lang', 'sourceLang', 'targetLang', 'inputText', 'maxLength'])
      .conflicts('negative-prompt', ['text', 'lang', 'sourceLang', 'targetLang', 'inputText', 'maxLength'])
      .conflicts('num-steps', ['text', 'lang', 'sourceLang', 'targetLang', 'inputText', 'maxLength'])
      .conflicts('prompt', ['text', 'sourceLang', 'targetLang', 'inputText', 'maxLength', 'image'])
      .conflicts('seed', ['text', 'lang', 'sourceLang', 'targetLang', 'inputText', 'maxLength'])
      .conflicts('strength', ['text', 'lang', 'sourceLang', 'targetLang', 'inputText', 'maxLength'])
      .conflicts('width', ['text', 'lang', 'sourceLang', 'targetLang', 'inputText', 'maxLength'])
      .conflicts('lang', [
        'text',
        'guidance',
        'height',
        'image',
        'imageB64',
        'mask',
        'negativePrompt',
        'numSteps',
        'seed',
        'strength',
        'width',
        'sourceLang',
        'targetLang',
        'inputText',
        'maxLength',
      ])
      .conflicts('source-lang', [
        'guidance',
        'height',
        'image',
        'imageB64',
        'mask',
        'negativePrompt',
        'numSteps',
        'prompt',
        'seed',
        'strength',
        'width',
        'lang',
        'inputText',
        'maxLength',
      ])
      .conflicts('target-lang', [
        'guidance',
        'height',
        'image',
        'imageB64',
        'mask',
        'negativePrompt',
        'numSteps',
        'prompt',
        'seed',
        'strength',
        'width',
        'lang',
        'inputText',
        'maxLength',
      ])
      .implies('target-lang', ['text'])
      .conflicts('input-text', [
        'text',
        'guidance',
        'height',
        'image',
        'imageB64',
        'mask',
        'negativePrompt',
        'numSteps',
        'prompt',
        'seed',
        'strength',
        'width',
        'lang',
        'sourceLang',
        'targetLang',
      ])
      .conflicts('max-length', [
        'text',
        'guidance',
        'height',
        'image',
        'imageB64',
        'mask',
        'negativePrompt',
        'numSteps',
        'prompt',
        'seed',
        'strength',
        'width',
        'lang',
        'sourceLang',
        'targetLang',
      ]) as Argv<RunArgs>;
  },

  handler: async (argv: ArgumentsCamelCase<RunArgs>): Promise<void> => {
    try {
      validateResourceId(argv.modelName as string | undefined, 'modelName');

      if (argv.dryRun) {
        if (argv.accountId) validateResourceId(argv.accountId, 'accountId');
        formatDryRun({
          command: 'cf ai run',
          method: 'POST',
          url: `https://api.cloudflare.com/client/v4/accounts/${argv.accountId ?? '<account-id>'}/ai/run/${argv.modelName ?? '<modelName>'}`,
          pathParams: { modelName: String(argv.modelName ?? '') },
          body: {
            text: argv.text,
            guidance: argv.guidance,
            height: argv.height,
            image: argv.image,
            imageB64: argv.imageB64,
            mask: argv.mask,
            negativePrompt: argv.negativePrompt,
            numSteps: argv.numSteps,
            prompt: argv.prompt,
            seed: argv.seed,
            strength: argv.strength,
            width: argv.width,
            lang: argv.lang,
            sourceLang: argv.sourceLang,
            targetLang: argv.targetLang,
            inputText: argv.inputText,
            maxLength: argv.maxLength,
          },
          validation: 'passed',
        });
        return;
      }
      const client = new Cloudflare({
        apiToken: await getAuthToken(),
        baseURL: process.env.CLOUDFLARE_BASE_URL,
        defaultHeaders: getDefaultHeaders(),
      });
      const accountId = await getAccountId({ accountId: argv.accountId }, client);

      if (argv.body) {
        const bodyData = parseBody(argv.body);
        const result = await client.post<unknown>(`/accounts/${accountId}/ai/run/${argv.modelName}`, {
          body: bodyData,
        });
        formatOutput(result, { fields: argv.fields, ndjson: argv.ndjson ?? false });
        return;
      }

      // Assemble request body from individual flags
      const bodyData: Record<string, unknown> = {};
      if (argv.text !== undefined) setNestedValue(bodyData, ['text'], argv.text);
      if (argv.guidance !== undefined) setNestedValue(bodyData, ['guidance'], argv.guidance);
      if (argv.height !== undefined) setNestedValue(bodyData, ['height'], argv.height);
      if (argv.image !== undefined) setNestedValue(bodyData, ['image'], argv.image);
      if (argv.imageB64 !== undefined) setNestedValue(bodyData, ['image_b64'], argv.imageB64);
      if (argv.mask !== undefined) setNestedValue(bodyData, ['mask'], argv.mask);
      if (argv.negativePrompt !== undefined) setNestedValue(bodyData, ['negative_prompt'], argv.negativePrompt);
      if (argv.numSteps !== undefined) setNestedValue(bodyData, ['num_steps'], argv.numSteps);
      if (argv.prompt !== undefined) setNestedValue(bodyData, ['prompt'], argv.prompt);
      if (argv.seed !== undefined) setNestedValue(bodyData, ['seed'], argv.seed);
      if (argv.strength !== undefined) setNestedValue(bodyData, ['strength'], argv.strength);
      if (argv.width !== undefined) setNestedValue(bodyData, ['width'], argv.width);
      if (argv.lang !== undefined) setNestedValue(bodyData, ['lang'], argv.lang);
      if (argv.sourceLang !== undefined) setNestedValue(bodyData, ['source_lang'], argv.sourceLang);
      if (argv.targetLang !== undefined) setNestedValue(bodyData, ['target_lang'], argv.targetLang);
      if (argv.inputText !== undefined) setNestedValue(bodyData, ['input_text'], argv.inputText);
      if (argv.maxLength !== undefined) setNestedValue(bodyData, ['max_length'], argv.maxLength);
      const result = await client.post<unknown>(`/accounts/${accountId}/ai/run/${argv.modelName}`, {
        body: Object.keys(bodyData).length > 0 ? bodyData : undefined,
      });
      formatOutput(result, { fields: argv.fields, ndjson: argv.ndjson ?? false });
    } catch (error) {
      handleError(error);
    }
  },
};

export default command;
