on:
  schedule:
    - cron: "50 * * * *"
  workflow_dispatch: {}

name: Mine Workerd
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Restore NPM cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('scripts/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install capnproto
        run: sudo apt-get update && sudo apt-get install -y capnproto libcapnp-dev

      - name: Clone workerd
        run: |
          mkdir -p temp
          git clone --depth 1 https://github.com/cloudflare/workerd.git temp/workerd

      - name: Parse and push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          cd scripts
          npm ci
          npm run mine:workerd
        env:
          DISCORD_WEBHOOK_WORKERD: ${{ secrets.DISCORD_WEBHOOK_WORKERD }}
